import type { Article } from "@/types/content";

const articleBody = (intro: string, bullets: string[]) => [
  { heading: "Start with the reader's task", paragraphs: [intro] },
  { heading: "A practical framework", paragraphs: ["Good work becomes easier to repeat when the important decisions are visible. Use a small, consistent structure, then adapt it to the context instead of adding process for its own sake."], bullets },
  { heading: "Keep improving the system", paragraphs: ["Treat the first version as a useful baseline. Review what helped, remove friction, and keep the parts that make the next iteration clearer."] },
];

export const latestArticles: Article[] = [
  { slug: "why-ats-rejects-most-resumes", title: "Why ATS Rejects Most Resumes (And How to Fix It)", description: "A practical look at making professional resumes clearer for people and screening systems.", category: "Career Tools", date: "May 14, 2025", isoDate: "2025-05-14", readingTime: "6 min read", href: "/blog/why-ats-rejects-most-resumes", tags: ["Career", "Templates"], body: articleBody("A resume has to work in two environments: a structured screening process and a human review. Clear hierarchy and specific evidence help it do both.", ["Use familiar section names and consistent formatting.", "Match language to the role without copying a job description.", "Make outcomes easy to scan in a few seconds."]) },
  { slug: "best-ats-resume-format-for-fresh-graduates", title: "Best ATS Resume Format for Fresh Graduates", description: "A simple, readable structure for presenting early experience with confidence.", category: "Career Tools", date: "May 07, 2025", isoDate: "2025-05-07", readingTime: "5 min read", href: "/blog/best-ats-resume-format-for-fresh-graduates", tags: ["Career", "Guides"], body: articleBody("When experience is early, structure does more work. A clear format lets projects, coursework, and practical skills support the story.", ["Lead with a concise profile and relevant skills.", "Give projects the same care as employment entries.", "Keep dates, headings, and links consistent."]) },
  { slug: "tailor-your-resume-for-each-job", title: "How to Tailor Your Resume for Each Job Without Rewriting It", description: "A repeatable way to adjust a resume for a role without starting from scratch.", category: "Career Tools", date: "Apr 30, 2025", isoDate: "2025-04-30", readingTime: "7 min read", href: "/blog/tailor-your-resume-for-each-job", tags: ["Career", "Workflow"], body: articleBody("Tailoring is faster when the source document is modular. Keep a strong base, then change the evidence that matters most for each role.", ["Maintain a master inventory of projects and outcomes.", "Prioritize the job's recurring responsibilities.", "Review the first third of the page for relevance."]) },
  { slug: "common-resume-mistakes", title: "Common Resume Mistakes That Kill Applications", description: "The avoidable clarity and formatting problems that make good experience harder to see.", category: "Career Tools", date: "Apr 22, 2025", isoDate: "2025-04-22", readingTime: "6 min read", href: "/blog/common-resume-mistakes", tags: ["Career", "Writing"], body: articleBody("Most resume problems are not dramatic. They are small inconsistencies that make the reader spend effort finding the signal.", ["Remove vague claims without supporting evidence.", "Reduce visual noise and unnecessary detail.", "Proofread links, dates, and role names."]) },
  { slug: "ats-resume-keywords", title: "ATS Resume Keywords: How to Find and Use Them", description: "A grounded approach to using relevant role language without keyword stuffing.", category: "Career Tools", date: "Apr 15, 2025", isoDate: "2025-04-15", readingTime: "6 min read", href: "/blog/ats-resume-keywords", tags: ["Career", "Research"], body: articleBody("Relevant language is useful when it describes real experience. The goal is alignment and clarity, not a list of disconnected terms.", ["Group repeated responsibilities into themes.", "Use the language you can support with examples.", "Prefer natural sentences over keyword lists."]) },
  { slug: "simple-resume-structure", title: "Simple Resume Structure That Works in Any Industry", description: "A flexible document structure that keeps attention on useful evidence.", category: "Career Tools", date: "Apr 08, 2025", isoDate: "2025-04-08", readingTime: "5 min read", href: "/blog/simple-resume-structure", tags: ["Career", "Templates"], body: articleBody("A reliable structure reduces decisions for both the writer and the reader. Keep the hierarchy stable and let the content carry the difference.", ["Use a clear header and short summary.", "Organize experience around outcomes and scope.", "Make skills specific and easy to verify."]) },
  { slug: "cover-letter-format-2026", title: "Cover Letter Format That Still Works in 2026", description: "A concise structure for connecting your experience to the work a role needs.", category: "Career Tools", date: "Apr 01, 2025", isoDate: "2025-04-01", readingTime: "6 min read", href: "/blog/cover-letter-format-2026", tags: ["Career", "Writing"], body: articleBody("A useful cover letter is a short argument for fit. It should make a specific connection rather than repeat the resume.", ["Open with the role and a precise reason for interest.", "Use one or two relevant examples.", "Close with a clear, professional next step."]) },
  { slug: "docker-deployment-checklist", title: "Docker Deployment Checklist for Small Projects", description: "The essential checks to make before shipping a small containerized application.", category: "Development", date: "Mar 25, 2025", isoDate: "2025-03-25", readingTime: "8 min read", href: "/blog/docker-deployment-checklist", tags: ["Development", "Docker"], body: articleBody("Small projects benefit from a deployment routine that is short enough to use and thorough enough to catch predictable mistakes.", ["Confirm environment values are supplied safely.", "Test the production image separately from local development.", "Document the rollback and health-check path."]) },
];

export function getArticle(slug: string) {
  return latestArticles.find((article) => article.slug === slug);
}
