import { ArrowRight, Boxes, CheckSquare, FolderKanban, Layers3, Sparkles } from "lucide-react";

import { ArticleCard, CategoryCard, ResourceCard, ToolCard } from "@/components/ui/Cards";
import { Container } from "@/components/ui/Container";
import { Button } from "@/components/ui/Button";
import { SectionHeading } from "@/components/ui/SectionHeading";
import { latestArticles } from "@/content/blog";
import { recommendedTools } from "@/content/products";
import { featuredResources } from "@/content/resources";

export default function Home() {
  return (
    <div>
      <section className="overflow-hidden border-b border-[var(--color-border)]"><Container className="grid gap-14 py-20 sm:py-28 lg:grid-cols-[1.1fr_0.9fr] lg:items-center lg:py-32"><div><p className="mb-6 text-xs font-bold uppercase tracking-[0.2em] text-[var(--color-accent)]">Atlas Studio</p><h1 className="max-w-3xl text-5xl font-semibold leading-[1.05] tracking-[-0.055em] text-[var(--color-foreground)] sm:text-7xl">Practical Digital Resources for Modern Work</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[var(--color-muted-foreground)]">Templates, guides, tools, and practical resources designed to help developers, creators, freelancers, and digital professionals work smarter.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Button href="/resources">Explore Resources <ArrowRight aria-hidden="true" size={17} /></Button><Button href="/blog" variant="secondary">Read the Blog</Button></div></div><div aria-hidden="true" className="relative mx-auto w-full max-w-md"><div className="aspect-square rounded-[1.5rem] border border-[var(--color-border)] bg-[var(--color-card)] p-5 shadow-[var(--shadow-md)]"><div className="flex items-center justify-between border-b border-[var(--color-border)] pb-4"><span className="font-mono text-xs text-[var(--color-muted-foreground)]">ATLAS / INDEX</span><span className="size-2 rounded-full bg-[var(--color-accent)]" /></div><div className="grid h-[calc(100%-3.25rem)] grid-cols-2 gap-3 pt-4"><div className="rounded-[var(--radius-md)] bg-[var(--color-primary)] p-4 text-[var(--color-primary-foreground)]"><span className="font-mono text-xs opacity-70">01</span><div className="mt-16 text-sm font-semibold">Learn</div></div><div className="rounded-[var(--radius-md)] border border-[var(--color-border)] p-4"><span className="font-mono text-xs text-[var(--color-muted-foreground)]">02</span><div className="mt-16 text-sm font-semibold">Build</div></div><div className="col-span-2 rounded-[var(--radius-md)] bg-[var(--color-accent-soft)] p-4"><div className="flex items-end justify-between"><span className="text-sm font-semibold text-[var(--color-foreground)]">Make progress visible.</span><span className="font-mono text-xs text-[var(--color-accent)]">[ ]</span></div><div className="mt-5 h-1.5 rounded-full bg-[var(--color-accent)]/25"><div className="h-full w-2/3 rounded-full bg-[var(--color-accent)]" /></div></div></div></div></div></Container></section>
      <section className="py-20 sm:py-28"><Container><SectionHeading title="Explore by Category" description="Start with a focused collection of ideas and tools for the work in front of you." /><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><CategoryCard title="Developer Resources" description="Build clearer, more maintainable software." icon={<Boxes size={20} />} /><CategoryCard title="AI & Automation" description="Make repetitive work more useful." icon={<Sparkles size={20} />} /><CategoryCard title="Digital Products" description="Turn useful ideas into assets." icon={<Layers3 size={20} />} /><CategoryCard title="Productivity" description="Create systems that keep work moving." icon={<FolderKanban size={20} />} /><CategoryCard title="Guides & Tutorials" description="Learn through practical examples." icon={<CheckSquare size={20} />} /></div></Container></section>
      <section className="border-y border-[var(--color-border)] bg-[var(--color-card-muted)] py-20 sm:py-28"><Container><SectionHeading title="Featured Resources" description="Practical resources built to save time and simplify digital work." /><div className="mt-10 grid gap-5 lg:grid-cols-3">{featuredResources.map((resource) => <ResourceCard key={resource.title} resource={resource} />)}</div></Container></section>
      <section className="py-20 sm:py-28"><Container><SectionHeading title="From the Blog" description="Clear thinking and useful patterns for modern digital work." /><div className="mt-10 grid gap-5 lg:grid-cols-3">{latestArticles.map((article) => <ArticleCard key={article.title} article={article} />)}</div></Container></section>
      <section className="border-y border-[var(--color-border)] bg-[var(--color-card-muted)] py-20 sm:py-28"><Container><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><SectionHeading title="Tools Worth Exploring" description="A considered shortlist of tools that help turn good intentions into repeatable practice." /><p className="text-xs text-[var(--color-muted-foreground)]">Some links may be affiliate links.</p></div><div className="mt-10 grid gap-5 lg:grid-cols-3">{recommendedTools.map((tool) => <ToolCard key={tool.name} tool={tool} />)}</div></Container></section>
      <section className="py-20 sm:py-28"><Container><div className="rounded-[var(--radius-lg)] border border-[var(--color-border)] bg-[var(--color-card)] p-8 shadow-[var(--shadow-sm)] sm:p-12"><div className="grid gap-10 lg:grid-cols-[1fr_0.8fr] lg:items-end"><SectionHeading title="Useful Ideas. Delivered Occasionally." description="Get practical resources, tools, and guides for modern digital work." /><form className="flex flex-col gap-3 sm:flex-row"><label htmlFor="newsletter-email" className="sr-only">Email address</label><input id="newsletter-email" name="email" type="email" required placeholder="you@example.com" className="min-h-11 flex-1 rounded-[var(--radius-md)] border border-[var(--color-border-strong)] bg-transparent px-4 text-sm text-[var(--color-foreground)] outline-none placeholder:text-[var(--color-muted-foreground)] focus:border-[var(--color-accent)] focus:ring-2 focus:ring-[var(--color-accent-soft)]" /><Button type="submit">Subscribe</Button></form></div></div></Container></section>
      <section className="border-t border-[var(--color-border)] bg-[var(--color-primary)] py-20 text-[var(--color-primary-foreground)] sm:py-28"><Container><div className="flex flex-col justify-between gap-8 sm:flex-row sm:items-end"><div><h2 className="max-w-xl text-4xl font-semibold tracking-[-0.04em] sm:text-5xl">Build smarter. Work faster.</h2><p className="mt-5 max-w-xl text-base leading-7 opacity-75">Explore practical resources created to save time and simplify digital work.</p></div><Button href="/" variant="secondary" className="border-[var(--color-primary-foreground)] text-[var(--color-primary-foreground)] hover:bg-[var(--color-primary-foreground)] hover:text-[var(--color-primary)]">Explore Atlas Studio <ArrowRight aria-hidden="true" size={17} /></Button></div></Container></section>
    </div>
  );
}
